version: '2.1'
orbs:
  aws-s3: circleci/aws-cli@3.1.4
jobs:
  build:
    docker:
      - image: 'cimg/node:18.9.0'
    steps:
      - checkout
      - run:
          name: Yarn Install
          command: yarn install
      - run:
          name: Install Dependencies
          command: yarn run build
workflows:
  build:
    jobs:
      - build

