version: '2.1'
orbs:
  aws-s3: circleci/aws-s3@3.1.1

workflows:
  build-deploy:
    jobs:
    - build
    - deploy:
        requires:
        - build
        filters:
          branches:
            only: main

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: 'cimg/node:18.9.0'
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: Run Tests
          command: yarn test
      - run:
          name: Install build
          command: yarn run build
  deploy:
    working_directory: ~/repo
    docker:
      - image: 'cimg/node:18.9.0'
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - aws-s3/sync:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-region: AWS_REGION
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          from: ~/repo/dist/
          to: 's3://stage.kdc'
      - aws-s3/copy:
          from: ~/repo/dist/
          to: 's3://stage.kdc'
