version: '2.1'
orbs:
  aws-cli: circleci/aws-cli@3.1.4

workflows:
  build-deploy:
    jobs:
    - build
    - deploy:
        requires:
        - build
        filters:
          branches:
            only: main

jobs:
  build:
    docker:
      - image: 'cimg/node:18.9.0'
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: Run Tests
          command: yarn test
      - run:
          name: Install build
          command: yarn run build
  deploy:
    docker:
      - image: 'cimg/node:18.9.0'
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - run:
          name: Deploy to S3
          command: aws s3 sync <path/to/bucket> <s3://location/in/S3-to-deploy-to>
