version: '2.1'
orbs:
  node: circleci/node@5.0.3
  aws-s3: circleci/aws-cli@3.1
jobs:
  install-node-example:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '18.9.0'
      - run:
          name: Yarn Install
          command: yarn install
      - run:
          name: Install Dependencies
          command: yarn run build
      - aws-s3/sync:
          from: dist
          to: 's3:kidclampdown.com'
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_REGION
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          overwrite: true
      - aws-s3/copy:
          from: dist
          to: 's3://kidclampdown.com'
          arguments: |
            --recursive
workflows:
  test_my_app:
    jobs:
      - install-node-example

