version: '2.1'
orbs:
  node: circleci/node@18.9.0
jobs:
  executor:
    name: node/default
  steps:
    - checkout
    - node/install:
        install-yarn: true
        node-version: '18.9.0'
        run: yarn run build
    - run: node --version

workflows:
  build-and-test:
    jobs:
      - build-and-test
